// Downloads the typefaces for the four design directions from Google Fonts
// (all under the SIL Open Font Licence) so sites can host them themselves:
// faster on phones, no third-party requests. Latin subset only.
import { mkdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const out = join(dirname(fileURLToPath(import.meta.url)), '../fonts');
mkdirSync(out, { recursive: true });
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0 Safari/537.36';
// Optical-size axes are pinned (display sizes for headline faces, text size for body faces):
// the files come out about half the size, which keeps phones on 4G under a second for type.
const FAMILIES = [
  ['Cormorant Garamond', 'ital,wght@0,300..700;1,300..700'],
  ['Jost', 'wght@300..700'],
  ['Bricolage Grotesque', 'opsz,wght@96,300..800'],
  ['DM Sans', 'opsz,wght@14,300..800'],
  ['Syne', 'wght@400..800'],
  ['Manrope', 'wght@300..800'],
  ['Fraunces', 'ital,opsz,wght@0,144,400..700;1,144,400..700'],
  ['Work Sans', 'wght@300..700'],
];
let css = '/* Self-hosted Google Fonts (SIL Open Font Licence 1.1). Generated by tools/fetch-fonts.mjs */\n';
for (const [family, axes] of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${family.replace(/ /g, '+')}:${axes}&display=swap`;
  const text = await (await fetch(url, { headers: { 'user-agent': UA } })).text();
  const blocks = text.split('/* ').filter((b) => b.startsWith('latin */'));
  for (const b of blocks) {
    const style = /font-style: (\w+)/.exec(b)[1];
    const weight = /font-weight: ([\d ]+)/.exec(b)[1];
    const src = /url\((https:[^)]+\.woff2)\)/.exec(b)[1];
    const range = /unicode-range: ([^;]+);/.exec(b)[1];
    const file = `${family.toLowerCase().replace(/ /g, '-')}-${style}.woff2`;
    const buf = Buffer.from(await (await fetch(src, { headers: { 'user-agent': UA } })).arrayBuffer());
    writeFileSync(join(out, file), buf);
    css += `@font-face{font-family:'${family}';font-style:${style};font-weight:${weight};font-display:swap;src:url(./${file}) format('woff2');unicode-range:${range}}\n`;
    console.log(`✓ ${file} ${(buf.length / 1024).toFixed(0)} KB`);
  }
}
writeFileSync(join(out, 'fonts.css'), css);
