// Downloads the typefaces for the design directions from Google Fonts
// (all under the SIL Open Font Licence) so sites can host them themselves:
// faster on phones, no third-party requests. Latin subset only.
import { mkdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const out = join(dirname(fileURLToPath(import.meta.url)), '../fonts');
mkdirSync(out, { recursive: true });
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0 Safari/537.36';
// Optical-size axes are pinned (display sizes for headline faces, text size for body faces):
// the files come out about half the size, which keeps phones on 4G under a second for type.
const FAMILIES = [
  ['Cormorant Garamond', 'ital,wght@0,300..700;1,300'], // italics are only used at 300
  ['Jost', 'wght@300..700'],
  ['Bricolage Grotesque', 'opsz,wght@96,300..800'],
  ['DM Sans', 'opsz,wght@14,300..800'],
  ['Syne', 'wght@400..800'],
  ['Manrope', 'wght@300..800'],
  ['Fraunces', 'ital,opsz,wght@0,144,400..700;1,144,500'], // italics are only used at 500
  ['Karla', 'wght@400..700'],
  ['Anton', 'wght@400'],
  ['Archivo', 'wght@400..800'],
  ['Instrument Serif', 'ital,wght@0,400;1,400'],
  ['Inter Tight', 'wght@300..700'],
  ['Mona Sans', 'wdth,wght@75..125,400..900'], // width stretches from narrow to extra-wide
  // Design kit 2.0: the type library each site's own pairing is chosen from.
  ['Bodoni Moda', 'ital,opsz,wght@0,96,400..800;1,96,400'],
  ['Hanken Grotesk', 'wght@300..700'],
  ['Playfair Display', 'ital,wght@0,400..800;1,400'],
  ['Source Sans 3', 'wght@300..700'],
  ['Libre Caslon Display', 'wght@400'],
  ['Libre Caslon Text', 'ital,wght@0,400;0,700;1,400'], // fixed weights, not a range
  ['Newsreader', 'ital,opsz,wght@0,36,300..700;1,36,400'],
  ['IBM Plex Mono', 'wght@400'],
  ['Gloock', 'wght@400'],
  ['Figtree', 'wght@300..800'],
  ['Young Serif', 'wght@400'],
  ['Onest', 'wght@300..800'],
  ['DM Serif Display', 'ital,wght@0,400;1,400'],
  ['Italiana', 'wght@400'],
  ['Space Grotesk', 'wght@300..700'],
  ['Space Mono', 'wght@400'],
  ['Unbounded', 'wght@300..900'],
  ['Bebas Neue', 'wght@400'],
  ['Libre Franklin', 'wght@300..800'],
  ['Epilogue', 'wght@300..900'],
  ['Outfit', 'wght@300..800'],
  ['Big Shoulders Display', 'wght@400..900'],
];
const written = new Set();
let css = '/* Self-hosted Google Fonts (SIL Open Font Licence 1.1). Generated by tools/fetch-fonts.mjs */\n';
for (const [family, axes] of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${family.replace(/ /g, '+')}:${axes}&display=swap`;
  const res = await fetch(url, { headers: { 'user-agent': UA } });
  if (!res.ok) throw new Error(`${family}: Google Fonts said ${res.status}. Check the family name and axes.`);
  const text = await res.text();
  const blocks = text.split('/* ').filter((b) => b.startsWith('latin */'));
  for (const b of blocks) {
    const style = /font-style: (\w+)/.exec(b)[1];
    const weight = /font-weight: ([\d ]+)/.exec(b)[1];
    const src = /url\((https:[^)]+\.woff2)\)/.exec(b)[1];
    const range = /unicode-range: ([^;]+);/.exec(b)[1];
    const stretch = /font-stretch: ([^;]+ [^;]+);/.exec(b)?.[1]; // only real width ranges
    // Fonts that come in fixed weights (e.g. regular and bold) get one file per extra weight.
    let file = `${family.toLowerCase().replace(/ /g, '-')}-${style}.woff2`;
    if (written.has(file)) file = file.replace('.woff2', `-${weight.trim()}.woff2`);
    written.add(file);
    const buf = Buffer.from(await (await fetch(src, { headers: { 'user-agent': UA } })).arrayBuffer());
    writeFileSync(join(out, file), buf);
    css += `@font-face{font-family:'${family}';font-style:${style};font-weight:${weight};${stretch ? `font-stretch:${stretch};` : ''}font-display:swap;src:url(./${file}) format('woff2');unicode-range:${range}}\n`;
    console.log(`✓ ${file} ${(buf.length / 1024).toFixed(0)} KB`);
  }
}
writeFileSync(join(out, 'fonts.css'), css);
