// Measures how wide each capital letter, digit and sign is in every pairing's headline font,
// so the renderer can size a business name to fill the screen exactly (the wordmark hero).
// Writes src/metrics.ts. Needs a browser; run after adding fonts:
//   NODE_PATH=../../node_modules/.pnpm/node_modules node tools/measure-fonts.mjs
import { chromium } from '@playwright/test';
import { readFileSync, writeFileSync } from 'node:fs';
import http from 'node:http';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const dir = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = readFileSync(join(dir, 'src/style.ts'), 'utf8');
const rows = [...src.matchAll(/^ {2}(\w+): \{ name: .*?display: (?:serif|sans|mono)\('([^']+)'\).*?weight: (\d+)/gm)]
  .map((m) => ({ id: m[1], family: m[2], weight: Number(m[3]) }));
const CHARS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 &\'’.,-!?:+@#';

// Fonts must come from a web address for the browser to load them.
const server = http.createServer((req, res) => {
  if (req.url === '/') { res.setHeader('content-type', 'text/html'); return res.end(`<style>${readFileSync(join(dir, 'fonts/fonts.css'), 'utf8')}</style>`); }
  try { res.setHeader('content-type', 'font/woff2'); res.end(readFileSync(join(dir, 'fonts', req.url.slice(1).replace(/[^\w.-]/g, '')))); } catch { res.statusCode = 404; res.end(); }
}).listen(0, '127.0.0.1');
await new Promise((r) => server.once('listening', r));
const browser = await chromium.launch();
const page = await browser.newPage();
await page.goto(`http://127.0.0.1:${server.address().port}/`);
const metrics = await page.evaluate(async ({ rows, CHARS }) => {
  const out = {};
  const ctx = document.createElement('canvas').getContext('2d');
  for (const r of rows) {
    const stretch = r.id === 'mona' ? 'expanded' : 'normal'; // the Colour block look stretches Mona Sans to 125%
    await document.fonts.load(`${r.weight} ${stretch} 100px "${r.family}"`, CHARS);
    if (!document.fonts.check(`${r.weight} 100px "${r.family}"`, 'A')) throw new Error(`${r.family} did not load`);
    ctx.font = `${r.weight} 1000px "${r.family}"`;
    ctx.fontStretch = stretch;
    out[r.id] = [...CHARS].map((c) => Math.round(ctx.measureText(c).width) / 1000);
  }
  return out;
}, { rows, CHARS });
await browser.close();
server.close();

const body = Object.entries(metrics).map(([id, w]) => `  ${id}: [${w.join(', ')}],`).join('\n');
writeFileSync(join(dir, 'src/metrics.ts'), `// Generated by tools/measure-fonts.mjs: the width (in em) of each character below, in capitals,
// in each pairing's headline font at its headline weight. Used to fit a business name to the screen.
export const METRIC_CHARS = ${JSON.stringify(CHARS)};
export const WIDTHS: Record<string, number[]> = {
${body}
};
`);
console.log(`Measured ${rows.length} fonts`);
